# Earth Meteorite Landings Analysis

## Task 1:
Extract programmatically the list of Earth Meteorite Landings from this dataset: [https://dmachek.github.io/meteorites-homework/meteorite_landings.json](https://dmachek.github.io/meteorites-homework/meteorite_landings.json)

Manual exploration first, downloading the file and visualizing it

```bash
wget -c https://dmachek.github.io/meteorites-homework/meteorite_landings.json](https://dmachek.github.io/meteorites-homework/meteorite_landings.json

yq -i meteorite_landings.json
```

- How many entries are in the dataset?

Task is possible with jq/yq (`yq '. | length' meteorite_landings.json`) or Python dictionary processing but I'm using Pandas for convenience

In [1]:
import pandas as pd
df = pd.read_json("meteorite_landings.json")
df.shape # returns number of rows and columns

(1000, 12)

# Answer is 1000

In [2]:
# Viewing data as entry
df.sample(5)

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation,:@computed_region_cbhk_fwbd,:@computed_region_nnqa_25f4
147,Bulls Run,5163,Valid,Iron?,2250.0,Fell,1964-01-01T00:00:00.000,NaN,NaN,NaN,NaN,NaN
566,Macibini,15372,Valid,Eucrite-pmict,1995.0,Fell,1936-01-01T00:00:00.000,-28.83333,31.95000,"{'latitude': '-28.83333', 'longitude': '31.95'}",NaN,NaN
842,Reliegos,22584,Valid,L5,17300.0,Fell,1947-01-01T00:00:00.000,42.47500,-5.33333,"{'latitude': '42.475', 'longitude': '-5.33333'}",NaN,NaN
614,Meuselbach,16626,Valid,L6,870.0,Fell,1897-01-01T00:00:00.000,50.58333,11.10000,"{'latitude': '50.58333', 'longitude': '11.1'}",NaN,NaN
803,Pnompehn,18851,Valid,L6,96.0,Fell,1868-01-01T00:00:00.000,11.58333,104.91667,"{'latitude': '11.58333', 'longitude': '104.916...",NaN,NaN

In [3]:
# Checking if all fields were assigned the right type, if not, I would do it manually
df.dtypes

name                               str
id                               int64
nametype                           str
recclass                           str
mass                           float64
fall                               str
year                               str
reclat                         float64
reclong                        float64
geolocation                     object
:@computed_region_cbhk_fwbd    float64
:@computed_region_nnqa_25f4    float64
dtype: object

In [4]:
# It seems fine for mass, I would convert years to datetime64 then to integer
df["year"] = pd.to_datetime(df["year"]).dt.year.astype("int64")

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [5]:
# There's a null value, let's fill it with zero
df["year"] = df["year"].fillna("01-01-01T00:00:00.000")

In [6]:
# Starting over
df["year"] = pd.to_datetime(df["year"], format="mixed").dt.year.astype("int64")
df["year"]

0      1880
1      1951
2      1952
3      1976
4      1902
       ...
995    1934
996    2011
997    1869
998    1922
999    1905
Name: year, Length: 1000, dtype: int64

- What is the name and mass of the most massive meteorite in this dataset?

In [7]:
df.sort_values(by="mass", ascending=False)[:1]

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation,:@computed_region_cbhk_fwbd,:@computed_region_nnqa_25f4
920,Sikhote-Alin,23593,Valid,"Iron, IIAB",23000000.0,Fell,1947,46.16,134.65333,"{'latitude': '46.16', 'longitude': '134.65333'}",NaN,NaN

# Answer is Sikhote-Alin , 23000000

- What is the most frequent year in this dataset?

In [8]:
df["year"].value_counts()

year
1933    16
1949    12
1930    11
1868    11
1976    10
        ..
1773     1
1794     1
1647     1
1623     1
1807     1
Name: count, Length: 247, dtype: int64

# Answer is 1933